# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='compression_ratio',
            new_name='compression_percentage',
        ),
    ]
