# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20170310_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='compressed_name',
            new_name='filename',
        ),
    ]
